# Generated by Django 4.2.9 on 2024-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_membernew_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernew',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
